/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sheldonluo_jnidemo_NativeMethod */

#ifndef _Included_com_example_sheldonluo_jnidemo_NativeMethod
#define _Included_com_example_sheldonluo_jnidemo_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sheldonluo_jnidemo_NativeMethod
 * Method:    print
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sheldonluo_jnidemo_NativeMethod_print
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_sheldonluo_jnidemo_NativeMethod
 * Method:    loadGif
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_sheldonluo_jnidemo_NativeMethod_loadGif
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_sheldonluo_jnidemo_NativeMethod
 * Method:    getNextFrame
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_example_sheldonluo_jnidemo_NativeMethod_getNextFrame
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
